/// Flutter icons AreaIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.

import 'package:flutter/widgets.dart';

class AreaIcons {

  AreaIcons._();

  static const _kFontFam = 'AreaIcons';
  static const String? _kFontPkg = null;

  static const IconData compass = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass_outline = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);

}
