version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
    # shows the container's output in the terminal if no -d flag
    stdin_open: true
    tty: true
