name: Epitech Repository Synchronization

on:
  push:
    branches:
      - main

env:
  MIRROR_URL: git@github.com:EpitechPGE3-2025/G-DEV-500-REN-5-1-area-5.git

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to Epitech repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
