name: Epitech Repository Synchronization

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Epitech repository
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote add epitech https://x-access-token:${{ secrets.EPITECH_REPOSITORY_TOKEN }}@github.com/EpitechPGE3-2025/G-DEV-500-REN-5-1-area-5.git
          git push --mirror --force epitech
