name: Epitech Repository Synchronization

on:
  push:
    branches:
      - main

env:
  MIRROR_URL: git@github.com:EpitechPGE3-2025/G-DEV-500-REN-5-1-area-5.git
  MIRROR_WIKI_URL: git@github.com:EpitechPGE3-2025/G-DEV-500-REN-5-1-area-5.wiki.git

jobs:
  sync-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to Epitech repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}

  sync-wiki:
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Checkout wiki repo
      run: |
        git clone --mirror "git@github.com:${{ github.repository }}.wiki.git" source.wiki
    - name: Push wiki to Epitech repository
      run: |
        cd source.wiki
        git push --mirror ${{ env.MIRROR_WIKI_URL }}
      env:
        GIT_SSH_COMMAND: 'ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no'
